### ISSUE TITLE
Google ID

### ISSUE THREAD

**Issue by npofopr** [MYchaieb/redmine_gc_sync#6]
Where to get this key:

Google Calendar ID Issue Delivery ?
Google Calendar ID Issues ?
Connection Code ?
refresh token ?

Google Calendar ID Global Delivery, Google Calendar ID Issue Delivery and Google Calendar ID Issues not the same thing?

**Comment by syncgit** [comment]
I have the same problem.
I found Connection code,refresh token and client secret but the Google Calendar ID ?
When I create the issue, in the log file, I saw the following error "Error while creating event on google calendar".

Any idea?

**Comment by MYchaieb** [comment]
Hey, 
I wrote something for that in the description.
https://github.com/MYchaieb/redmine_gc_sync#find-your-calendar-id

**Comment by npofopr** [comment]
In total:
Google Calendar ID Issue Delivery - this another calendar?
Google Calendar ID Issues - this another calendar? 
Connection Code - that is it?

**Comment by syncgit** [comment]
This is my ID : baraby.info@gmail.com?
Not work.
I followed your guide, but It doesn't work.

**Comment by npofopr** [comment]
@syncgit Google Calendar ID Global Delivery is not gmail, this is calendar ID https://docs.simplecalendar.io/find-google-calendar-id/

But I dont now that is it Google Calendar ID Issue Delivery, Google Calendar ID Issues, Connection Code.

**Comment by MYchaieb** [comment]
there are 3 calendar ID to fill in, 
Global Delivery have its own calendar 
Issue Delivery have its own calendar 
Issue have its own calendar. 
the connection code is a code that allow the Google Calendar API that i used in this project to connect to your Main calendar and its sub_calendars that you will create ( Global delivery, issue delivery and issue) 
(at the left menu you have my calendars etc ... you can create them from there)
you have just to follow the first step in the plugin configuration to get that code. 

1 - Fill first you Cliend ID, Client Secret and Calendar IDs and the click on apply. A link will appear to have your connection code
2 - Click on the link, you'll be redirected to a google page to autorise the app to communicate with your calendar. Copy and paste the code you'll find in connection code field and click on apply
etc ...

**Comment by syncgit** [comment]
Follow this guide...only step 1
https://developers.google.com/google-apps/calendar/quickstart/ruby

You can create the credential for google api...

**Comment by syncgit** [comment]
@MYchaieb 
I followed your steps, but it doesn't work.
how to create the auth on google api?
Id Client OAuth?
And also.
When you create the crendentials, have you used the json file?

I tried many times and now i'm so much confused! :/

Thanks

**Comment by npofopr** [comment]
I am completed! :) 
@syncgit write my steps?

**Comment by syncgit** [comment]
Me too!
I have only a problem.
When it saves the issue on the destination calendar, it writes it on midnight.
